version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    restart: always
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
    networks:
      - laravel-network

  
  db:
    
    image: mysql:latest

    platform: linux/amd64  # Добавляем эту строку
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: iHWW7kw9Tre25cn
      MYSQL_DATABASE: if0_38222624_php_work
      MYSQL_USER: if0_38222624
      MYSQL_PASSWORD: iHWW7kw9Tre25cn
    ports:
      - "3306:3306"

    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel-network

volumes:
  dbdata:

networks:
  laravel-network:
    driver: bridge
